server:
  port: 80

spring:
  datasource:
    hikari:
      connection-test-query: select 1
      connection-timeout: 60000
      validation-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 40
      idle-timeout: 600000
      auto-commit: true
      pool-name: HikariCP
    url: jdbc:mysql://192.168.110.201:3306/security?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    serialization:
      indent-output: true
  security:
    user:
      name: admin
      password: $2a$12$RfpBojc69rvrrlyZDC2fLeJCZSfurmLbbh19tmV6mWQxFutbD6lUK
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: order
  api-docs:
    path: /v3/api-docs # 不可变org.springdoc.core.utils.Constants#DEFAULT_SERVER_DESCRIPTION
  group-configs:
    - group: 'default'
      display-name: '测试'
      paths-to-match: '/test/**'
      packages-to-scan: com.example.jdk21.controller
    - group: 'user'
      display-name: '用户'
      paths-to-match: '/user/**'
      packages-to-scan: com.example.jdk21.controller
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  documents:
    - name: 标题1
      locations: classpath:markdown/*
      group: 测试
    - name: 标题2
      locations: classpath:markdown1/*
      group: 用户
  basic:
    enable: false
    username: abc
    password: 123